### ISSUE TITLE
Client fully crashes on 1.19.2 then clicking on a spawner

### ISSUE THREAD

**Issue by A-wolf** [embeddedt/Apogee#2]
Hi i tried using the mod on my server and just kept running into client (not server) crashes whenever i interacted with the mod. After a bit of testing did i discover that it was happening in single player too. To make sure it wasn't a mod conflict or a resource pack issue did i create a new profile with only apogee, fabric api and REI with dependencies to a brand new profile and the same still happened.

here is my console and crash report files, all mods where downloaded on modrith with the atlauncher 

Log: https://paste.atlauncher.com/view/f5beac96-df33-483f-a288-173a27f69e4c

Crash report: [see attachment]
[crash-2023-01-03_14.55.12-client.txt](https://github.com/embeddedt/Apogee/files/10337123/crash-2023-01-03_14.55.12-client.txt)

**Comment by A-wolf** [comment]
Thought i quickly add this i tried with only apogee-0.4.0.jar and fabric-api-0.71.0+1.19.2.jar installed and same result

**Comment by noahhead** [comment]
I'm having the same issue. As soon as I click on any spawner, the client crashes.

**Comment by embeddedt** [comment]
Sorry about that everyone! This is fixed in 0.4.1 - should be available on CurseForge shortly.
